### PR TITLE
Rising / Falling / Change modes and extra callbacks parameters

### PR DESCRIPTION
**Pull request by paulo-raca**
Hello, @SodaqMoja and @GabrielNotman

Thanks for this nice library.

Unfortunately, it didn't provide all the features I needed, so I'm wriiting some code ;)

I've started with @GabrielNotman's fork, which adds modes for Rising / Falling / Change, and added context parameters to the callbacks (Plus some minor refactoring, cleanup and fixes)

Would you like to merge it, or is it different enough that it should become a separate library?

### CODE REVIEW

**Comment by keestux** [comment]
Great.

It looks like you did quit a lot of work on it. (In just one day? Huh?)

Just so you know, the reason why Gabriels changes were not incorporated was that the timing for software serial was not good. How well does your version behave with our Sodaq_SoftSerial?
BTW. The most import reason for us to have this Sodaq_PcInt library was driven by the need in combination with software serial. And that's why we have a Sodaq_SoftSerial.

The PcInt library must be generic and fast. I'm pretty sure that you've done excellent on the generic part. Let me know how well it behaves on the "fast" requirement.

**Comment by paulo-raca** [comment]
That was a very productive day :D

I tested my changes with Sodaq_SoftSerial today
I had to adjust the timming of the first bit, but I managed to have it working up to 9600bps.
With some patience and a logic analyzer it might be possible to go a bit higher.

**Comment by SodaqMoja** [comment]
Yeah, higher speeds were a problem. I have forgotten how fast we could get it.

**Comment by paulo-raca** [comment]
The original library work on up to 19200bps.

I'll close this PR and maintain these changes as a separate library
Thanks!

**Comment by SodaqMoja** [comment]
Snif

Well, thank you for trying.

**Pull request closed without merging**
